wandb_version: 1

outer_policy_lr:
  desc: null
  value: 0.0001
outer_value_lr:
  desc: null
  value: 1.0e-05
inner_policy_lr:
  desc: null
  value: 0.001
inner_value_lr:
  desc: null
  value: 0.001
inner_buffer_size:
  desc: null
  value: -1
outer_buffer_size:
  desc: null
  value: -1
weight_transform:
  desc: null
  value: true
task_config:
  desc: null
  value: task_config/arc.json
advantage_head_coef:
  desc: null
  value: 0.001
net_width:
  desc: null
  value: 128
net_depth:
  desc: null
  value: 3
device:
  desc: null
  value: cuda
outer_batch_size:
  desc: null
  value: 4
inner_batch_size:
  desc: null
  value: 4
rollout_interval:
  desc: null
  value: 2500
model_save_interval:
  desc: null
  value: 2500
finetune_steps:
  desc: null
  value: 2500
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698675176.607509
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
