outer_policy_lr: 1e-4
outer_value_lr: 1e-5
inner_policy_lr: 1e-3
inner_value_lr: 1e-3
inner_buffer_size: -1
outer_buffer_size: -1
weight_transform: True
task_config: task_config/arc.json
advantage_head_coef: 1e-3
net_width: 128
net_depth: 3
device: cuda
outer_batch_size: 4
inner_batch_size: 4
rollout_interval: 250